// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pabtjngmuskflegxtahh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhYnRqbmdtdXNrZmxlZ3h0YWhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MDY3MzUsImV4cCI6MjA2NDM4MjczNX0.FG7tfo7kNwePDKKCkeVDulYCIdFUVYOz6Zm6SahaZO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);